// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/bank/service.proto

package bank

import (
	_type "github.com/raghav-gkmit/go-proto-buf/protogen/go/bank/type"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_bank_service_proto protoreflect.FileDescriptor

const file_proto_bank_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/bank/service.proto\x12\x04bank\x1a\x1dproto/bank/type/account.proto\x1a\x1eproto/bank/type/exchange.proto\x1a!proto/bank/type/transaction.proto2\x8e\x02\n" +
	"\vBankService\x12X\n" +
	"\x11GetCurrentBalance\x12 .bank.type.CurrentBalanceRequest\x1a!.bank.type.CurrentBalanceResponse\x12T\n" +
	"\x0fGetExchangeRate\x12\x1e.bank.type.ExchangeRateRequest\x1a\x1f.bank.type.ExchangeRateResponse0\x01\x12O\n" +
	"\x14SummarizeTransaction\x12\x16.bank.type.Transaction\x1a\x1d.bank.type.TransactionSummary(\x01B7Z5github.com/raghav-gkmit/go-proto-buf/protogen/go/bankb\x06proto3"

var file_proto_bank_service_proto_goTypes = []any{
	(*_type.CurrentBalanceRequest)(nil),  // 0: bank.type.CurrentBalanceRequest
	(*_type.ExchangeRateRequest)(nil),    // 1: bank.type.ExchangeRateRequest
	(*_type.Transaction)(nil),            // 2: bank.type.Transaction
	(*_type.CurrentBalanceResponse)(nil), // 3: bank.type.CurrentBalanceResponse
	(*_type.ExchangeRateResponse)(nil),   // 4: bank.type.ExchangeRateResponse
	(*_type.TransactionSummary)(nil),     // 5: bank.type.TransactionSummary
}
var file_proto_bank_service_proto_depIdxs = []int32{
	0, // 0: bank.BankService.GetCurrentBalance:input_type -> bank.type.CurrentBalanceRequest
	1, // 1: bank.BankService.GetExchangeRate:input_type -> bank.type.ExchangeRateRequest
	2, // 2: bank.BankService.SummarizeTransaction:input_type -> bank.type.Transaction
	3, // 3: bank.BankService.GetCurrentBalance:output_type -> bank.type.CurrentBalanceResponse
	4, // 4: bank.BankService.GetExchangeRate:output_type -> bank.type.ExchangeRateResponse
	5, // 5: bank.BankService.SummarizeTransaction:output_type -> bank.type.TransactionSummary
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bank_service_proto_init() }
func file_proto_bank_service_proto_init() {
	if File_proto_bank_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_service_proto_rawDesc), len(file_proto_bank_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bank_service_proto_goTypes,
		DependencyIndexes: file_proto_bank_service_proto_depIdxs,
	}.Build()
	File_proto_bank_service_proto = out.File
	file_proto_bank_service_proto_goTypes = nil
	file_proto_bank_service_proto_depIdxs = nil
}
