// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/bank/type/exchange.proto

package _type

import (
	google "github.com/raghav-gkmit/go-proto-buf/protogen/go/google"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateRequest) Reset() {
	*x = ExchangeRateRequest{}
	mi := &file_proto_bank_type_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateRequest) ProtoMessage() {}

func (x *ExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*ExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type ExchangeRateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency    string                 `protobuf:"bytes,1,opt,name=from_currency,proto3" json:"from_currency,omitempty"`
	ToCurrency      string                 `protobuf:"bytes,2,opt,name=to_currency,proto3" json:"to_currency,omitempty"`
	Rate            float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	LastUpdatedDate *google.Date           `protobuf:"bytes,4,opt,name=last_updated_date,json=last_updated,proto3" json:"last_updated_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExchangeRateResponse) Reset() {
	*x = ExchangeRateResponse{}
	mi := &file_proto_bank_type_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateResponse) ProtoMessage() {}

func (x *ExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*ExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeRateResponse) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRateResponse) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ExchangeRateResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ExchangeRateResponse) GetLastUpdatedDate() *google.Date {
	if x != nil {
		return x.LastUpdatedDate
	}
	return nil
}

var File_proto_bank_type_exchange_proto protoreflect.FileDescriptor

const file_proto_bank_type_exchange_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/bank/type/exchange.proto\x12\tbank.type\x1a\x1cproto/google/type/date.proto\"]\n" +
	"\x13ExchangeRateRequest\x12$\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\rfrom_currency\x12 \n" +
	"\vto_currency\x18\x02 \x01(\tR\vto_currency\"\xae\x01\n" +
	"\x14ExchangeRateResponse\x12$\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\rfrom_currency\x12 \n" +
	"\vto_currency\x18\x02 \x01(\tR\vto_currency\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12:\n" +
	"\x11last_updated_date\x18\x04 \x01(\v2\x11.google.type.DateR\flast_updatedB<Z:github.com/raghav-gkmit/go-proto-buf/protogen/go/bank/typeb\x06proto3"

var (
	file_proto_bank_type_exchange_proto_rawDescOnce sync.Once
	file_proto_bank_type_exchange_proto_rawDescData []byte
)

func file_proto_bank_type_exchange_proto_rawDescGZIP() []byte {
	file_proto_bank_type_exchange_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_exchange_proto_rawDesc), len(file_proto_bank_type_exchange_proto_rawDesc)))
	})
	return file_proto_bank_type_exchange_proto_rawDescData
}

var file_proto_bank_type_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bank_type_exchange_proto_goTypes = []any{
	(*ExchangeRateRequest)(nil),  // 0: bank.type.ExchangeRateRequest
	(*ExchangeRateResponse)(nil), // 1: bank.type.ExchangeRateResponse
	(*google.Date)(nil),          // 2: google.type.Date
}
var file_proto_bank_type_exchange_proto_depIdxs = []int32{
	2, // 0: bank.type.ExchangeRateResponse.last_updated_date:type_name -> google.type.Date
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bank_type_exchange_proto_init() }
func file_proto_bank_type_exchange_proto_init() {
	if File_proto_bank_type_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_exchange_proto_rawDesc), len(file_proto_bank_type_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_exchange_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_exchange_proto_depIdxs,
		MessageInfos:      file_proto_bank_type_exchange_proto_msgTypes,
	}.Build()
	File_proto_bank_type_exchange_proto = out.File
	file_proto_bank_type_exchange_proto_goTypes = nil
	file_proto_bank_type_exchange_proto_depIdxs = nil
}
